import type {
  AttentionItem,
  ContentTask,
  DashboardMetrics,
  IdeaExploration,
  LaunchChecklist,
  PriorityItem,
  Product,
  Project,
  PurchaseOrder,
  ShopifyOrder,
  Vendor,
} from "./types";

export const products: Product[] = [
  {
    id: "p1",
    name: "Muruga Water Bottle — 750ml",
    category: "Water bottles",
    world: "Muruga",
    sku: "AAR-BOT-MUR-750",
    sellingPrice: 890,
    cost: 320,
    inventory: 42,
    status: "Active",
    velocity: "Fast",
  },
  {
    id: "p2",
    name: "Lakshmi Brass Davara Tumbler",
    category: "Brass davara tumblers",
    world: "Lakshmi",
    sku: "AAR-BRS-LAK-01",
    sellingPrice: 1450,
    cost: 680,
    inventory: 18,
    status: "Active",
    velocity: "Steady",
  },
  {
    id: "p3",
    name: "Ganapathi Fridge Magnet Set",
    category: "Magnets",
    world: "Ganapathi",
    sku: "AAR-MAG-GAN-04",
    sellingPrice: 350,
    cost: 95,
    inventory: 210,
    status: "Active",
    velocity: "Fast",
  },
  {
    id: "p4",
    name: "Chennai Market Tote",
    category: "Tote bags",
    world: "Chennai",
    sku: "AAR-TOT-CHN-01",
    sellingPrice: 780,
    cost: 290,
    inventory: 64,
    status: "Active",
    velocity: "Steady",
  },
  {
    id: "p5",
    name: "Carnatic Raga Tray",
    category: "Trays",
    world: "Carnatic music",
    sku: "AAR-TRY-CAR-02",
    sellingPrice: 1680,
    cost: 720,
    inventory: 11,
    status: "Low stock",
    velocity: "Slow",
  },
  {
    id: "p6",
    name: "Bharatanatyam Gesture Pouch",
    category: "Pouches",
    world: "Bharatanatyam",
    sku: "AAR-POU-BHA-01",
    sellingPrice: 520,
    cost: 180,
    inventory: 88,
    status: "Active",
    velocity: "Steady",
  },
  {
    id: "p7",
    name: "Amman Stories — Children's Book",
    category: "Children's books",
    world: "Navarathri",
    sku: "AAR-BOK-AMM-01",
    sellingPrice: 499,
    cost: 165,
    inventory: 120,
    status: "Active",
    velocity: "Fast",
  },
  {
    id: "p8",
    name: "Kolam Framed Art — 12x16",
    category: "Framed art",
    world: "Chennai",
    sku: "AAR-ART-KOL-12",
    sellingPrice: 2200,
    cost: 890,
    inventory: 7,
    status: "Low stock",
    velocity: "Slow",
  },
];

export const vendors: Vendor[] = [
  {
    id: "v1",
    name: "Sri Velan Bottles",
    city: "Chennai",
    specialty: "Printed steel & BPA-free bottles",
    moq: 100,
    leadTimeDays: 18,
    rating: 4.6,
  },
  {
    id: "v2",
    name: "Moradabad Brass Collective",
    city: "Moradabad",
    specialty: "Brass tumblers, trays, ritual objects",
    moq: 50,
    leadTimeDays: 28,
    rating: 4.8,
  },
  {
    id: "v3",
    name: "Pondy Print House",
    city: "Puducherry",
    specialty: "Magnets, stickers, small print runs",
    moq: 200,
    leadTimeDays: 12,
    rating: 4.4,
  },
  {
    id: "v4",
    name: "Kanchi Weave Studio",
    city: "Kanchipuram",
    specialty: "Totes, pouches, textile gifts",
    moq: 75,
    leadTimeDays: 21,
    rating: 4.7,
  },
  {
    id: "v5",
    name: "Madurai Frame Works",
    city: "Madurai",
    specialty: "Framed art, print finishing",
    moq: 25,
    leadTimeDays: 14,
    rating: 4.5,
  },
];

export const purchaseOrders: PurchaseOrder[] = [
  {
    id: "PO-2401",
    vendorId: "v1",
    vendorName: "Sri Velan Bottles",
    productName: "Muruga Water Bottle — 750ml",
    quantityOrdered: 200,
    quantityReceived: 0,
    unitCost: 320,
    status: "In Production",
    requiredDate: "2026-08-10",
    orderedDate: "2026-07-01",
  },
  {
    id: "PO-2402",
    vendorId: "v3",
    vendorName: "Pondy Print House",
    productName: "Navarathri Magnet Assortment",
    quantityOrdered: 500,
    quantityReceived: 0,
    unitCost: 85,
    status: "Shipped",
    requiredDate: "2026-07-28",
    orderedDate: "2026-07-05",
  },
  {
    id: "PO-2398",
    vendorId: "v2",
    vendorName: "Moradabad Brass Collective",
    productName: "Lakshmi Brass Davara Tumbler",
    quantityOrdered: 80,
    quantityReceived: 72,
    unitCost: 680,
    status: "Partial",
    requiredDate: "2026-07-15",
    orderedDate: "2026-06-10",
  },
  {
    id: "PO-2395",
    vendorId: "v4",
    vendorName: "Kanchi Weave Studio",
    productName: "Chennai Market Tote",
    quantityOrdered: 150,
    unitCost: 290,
    status: "Sent",
    requiredDate: "2026-08-20",
    orderedDate: "2026-07-12",
  },
];

export const shopifyOrders: ShopifyOrder[] = [
  {
    id: "ORD-8841",
    customer: "Priya Raman",
    products: [
      { name: "Muruga Water Bottle — 750ml", qty: 2 },
      { name: "Ganapathi Fridge Magnet Set", qty: 1 },
    ],
    paymentStatus: "Paid",
    orderDate: "2026-07-21",
    deliveryCity: "Bengaluru",
    packageWeightKg: 1.2,
    courierStatus: "Awaiting Pack",
    total: 2130,
  },
  {
    id: "ORD-8837",
    customer: "Ananya Krishnan",
    products: [{ name: "Lakshmi Brass Davara Tumbler", qty: 1 }],
    paymentStatus: "Paid",
    orderDate: "2026-07-21",
    deliveryCity: "Chennai",
    packageWeightKg: 0.8,
    courierStatus: "Awaiting Pack",
    total: 1450,
  },
  {
    id: "ORD-8832",
    customer: "Rahul Menon",
    products: [
      { name: "Chennai Market Tote", qty: 1 },
      { name: "Amman Stories — Children's Book", qty: 2 },
    ],
    paymentStatus: "COD",
    orderDate: "2026-07-20",
    deliveryCity: "Kochi",
    packageWeightKg: 1.5,
    courierStatus: "Packed",
    total: 1778,
  },
  {
    id: "ORD-8825",
    customer: "Meera Subramanian",
    products: [{ name: "Kolam Framed Art — 12x16", qty: 1 }],
    paymentStatus: "Paid",
    orderDate: "2026-07-19",
    deliveryCity: "Hyderabad",
    packageWeightKg: 2.1,
    courierStatus: "Pickup Scheduled",
    total: 2200,
  },
  {
    id: "ORD-8818",
    customer: "Kumon Learning Centre",
    products: [
      { name: "Chennai Market Tote", qty: 10 },
      { name: "Ganapathi Fridge Magnet Set", qty: 20 },
    ],
    paymentStatus: "Pending",
    orderDate: "2026-07-18",
    deliveryCity: "Chennai",
    packageWeightKg: 8.4,
    courierStatus: "Awaiting Pack",
    total: 14800,
  },
];

export const projects: Project[] = [
  {
    id: "prj-1",
    name: "Muruga World Launch",
    status: "Manufacturing",
    deadline: "2026-09-01",
    budget: 350000,
    capitalCommitted: 214000,
    linkedProducts: ["Muruga Water Bottle — 750ml", "Muruga Magnet Set", "Muruga Story Card"],
    vendors: ["Sri Velan Bottles", "Pondy Print House"],
    tasks: [
      { id: "t1", title: "Approve bottle artwork v3", done: true },
      { id: "t2", title: "Confirm magnet colourways", done: false, due: "2026-07-25" },
      { id: "t3", title: "Draft launch email", done: false, due: "2026-08-15" },
      { id: "t4", title: "Shoot product photography", done: false, due: "2026-08-10" },
    ],
    manufacturingOrders: ["PO-2401"],
    contentTasks: ["ct-1", "ct-4"],
    risks: ["Bottle print colour may shift on navy body", "Photography slot not booked"],
    notes: "Lead world for Navarathri season. Pair bottles with magnets for gift sets.",
    world: "Muruga",
  },
  {
    id: "prj-2",
    name: "Kumon Chennai Hampers",
    status: "In Progress",
    deadline: "2026-08-05",
    budget: 185000,
    capitalCommitted: 92000,
    linkedProducts: ["Chennai Market Tote", "Ganapathi Fridge Magnet Set", "Amman Stories — Children's Book"],
    vendors: ["Kanchi Weave Studio"],
    tasks: [
      { id: "t5", title: "Finalise hamper SKU mix", done: true },
      { id: "t6", title: "Print thank-you cards", done: false, due: "2026-07-28" },
      { id: "t7", title: "Schedule dispatch window", done: false, due: "2026-08-02" },
    ],
    manufacturingOrders: [],
    contentTasks: ["ct-3"],
    risks: ["Institutional invoice pending"],
    notes: "100 hampers for teacher appreciation. Client wants Chennai + learning motif.",
    world: "Chennai",
  },
  {
    id: "prj-3",
    name: "Chalanam 2026 Merchandise",
    status: "Planning",
    deadline: "2026-11-15",
    budget: 420000,
    capitalCommitted: 45000,
    linkedProducts: ["Bharatanatyam Gesture Pouch", "Event Tote — Chalanam"],
    vendors: ["Kanchi Weave Studio", "Pondy Print House"],
    tasks: [
      { id: "t8", title: "Collect motif references from organisers", done: true },
      { id: "t9", title: "Propose 3 merch tiers", done: false, due: "2026-07-30" },
    ],
    manufacturingOrders: [],
    contentTasks: [],
    risks: ["Organiser logo guidelines not received"],
    notes: "Dance festival merch. Emphasise mudras and rhythm without costume clichés.",
    world: "Bharatanatyam",
  },
  {
    id: "prj-4",
    name: "Varalakshmi Collection",
    status: "Ideation",
    deadline: "2026-08-20",
    budget: 275000,
    capitalCommitted: 0,
    linkedProducts: ["Lakshmi Brass Davara Tumbler"],
    vendors: ["Moradabad Brass Collective"],
    tasks: [
      { id: "t10", title: "Moodboard for Varalakshmi morning rituals", done: false, due: "2026-07-26" },
      { id: "t11", title: "Price brass line for festival drop", done: false },
    ],
    manufacturingOrders: [],
    contentTasks: ["ct-2"],
    risks: ["Short window before festival"],
    notes: "Extend Lakshmi world into a focused festival capsule.",
    world: "Lakshmi",
  },
  {
    id: "prj-5",
    name: "Moradabad Sourcing Trip",
    status: "In Progress",
    deadline: "2026-08-12",
    budget: 85000,
    capitalCommitted: 32000,
    linkedProducts: ["Lakshmi Brass Davara Tumbler", "Carnatic Raga Tray"],
    vendors: ["Moradabad Brass Collective"],
    tasks: [
      { id: "t12", title: "Book travel & stay", done: true },
      { id: "t13", title: "Prepare vendor visit checklist", done: false, due: "2026-07-27" },
      { id: "t14", title: "Sample finish comparisons", done: false, due: "2026-08-08" },
    ],
    manufacturingOrders: ["PO-2398"],
    contentTasks: [],
    risks: ["Monsoon travel delays"],
    notes: "Focus on finish consistency and MOQ flexibility for trays.",
    world: "Lakshmi",
  },
];

export const contentTasks: ContentTask[] = [
  {
    id: "ct-1",
    title: "Muruga bottle — shelf story reel",
    product: "Muruga Water Bottle — 750ml",
    world: "Muruga",
    platform: "Instagram",
    format: "Reel",
    dueDate: "2026-07-28",
    status: "In Production",
    captionDraft:
      "A bottle that carries a story. Muruga — for the desk, the studio, the temple steps.",
    assets: [
      { label: "Product hero clip", done: true },
      { label: "Caption draft", done: true },
      { label: "Cover frame", done: false },
      { label: "Music clearance", done: false },
    ],
  },
  {
    id: "ct-2",
    title: "Varalakshmi morning LinkedIn note",
    product: "Lakshmi Brass Davara Tumbler",
    world: "Lakshmi",
    platform: "LinkedIn",
    format: "LinkedIn post",
    dueDate: "2026-08-01",
    status: "Draft",
    captionDraft:
      "Founders often ask how culture becomes product. For us, it starts with a morning object.",
    assets: [
      { label: "Photo set", done: false },
      { label: "Caption draft", done: true },
      { label: "CTA link", done: false },
    ],
  },
  {
    id: "ct-3",
    title: "Kumon hamper WhatsApp creative",
    product: "Chennai Market Tote",
    world: "Chennai",
    platform: "WhatsApp",
    format: "WhatsApp creative",
    dueDate: "2026-07-26",
    status: "Review",
    captionDraft: "A Chennai-rooted thank-you for the teachers who shape young minds.",
    assets: [
      { label: "Square creative", done: true },
      { label: "Hamper flat-lay", done: true },
      { label: "Client approval", done: false },
    ],
  },
  {
    id: "ct-4",
    title: "Culture Conversation — Navarathri objects",
    world: "Navarathri",
    platform: "Instagram",
    format: "Culture Conversation",
    dueDate: "2026-08-08",
    status: "Idea",
    captionDraft: "What objects hold Navarathri for you — beyond the altar?",
    assets: [
      { label: "Interview outline", done: false },
      { label: "Guest confirmed", done: false },
    ],
  },
  {
    id: "ct-5",
    title: "Aarla Pick — Ganapathi magnets",
    product: "Ganapathi Fridge Magnet Set",
    world: "Ganapathi",
    platform: "Pinterest",
    format: "Aarla Pick",
    dueDate: "2026-07-30",
    status: "Scheduled",
    captionDraft: "Small beginnings, pinned to the everyday.",
    assets: [
      { label: "Pin graphic", done: true },
      { label: "Product link", done: true },
    ],
  },
];

export const priorities: PriorityItem[] = [
  {
    id: "pr1",
    title: "Receive PO-2402 magnets from Pondy",
    source: "Receive Stock",
    urgency: "High",
    href: "/receive",
  },
  {
    id: "pr2",
    title: "Dispatch Kumon institutional order",
    source: "Dispatch Orders",
    urgency: "High",
    href: "/dispatch",
  },
  {
    id: "pr3",
    title: "Approve Muruga bottle artwork",
    source: "Manufacture",
    urgency: "Medium",
    href: "/manufacture",
  },
  {
    id: "pr4",
    title: "Finish Kumon WhatsApp creative review",
    source: "Content Studio",
    urgency: "Medium",
    href: "/content",
  },
];

export const attentionItems: AttentionItem[] = [
  {
    id: "a1",
    title: "Partial brass delivery — 8 tumblers missing",
    detail: "PO-2398 from Moradabad Brass Collective",
    tone: "warning",
    href: "/receive",
  },
  {
    id: "a2",
    title: "Kolam framed art at 7 units",
    detail: "Below reorder threshold for Slow movers",
    tone: "danger",
    href: "/manufacture",
  },
  {
    id: "a3",
    title: "ORD-8818 payment still pending",
    detail: "Kumon Learning Centre — ₹14,800",
    tone: "warning",
    href: "/dispatch",
  },
  {
    id: "a4",
    title: "Muruga photography not booked",
    detail: "Blocks launch checklist readiness",
    tone: "info",
    href: "/launch",
  },
];

export const dashboardMetrics: DashboardMetrics = {
  revenue: 684200,
  revenueChange: 12.4,
  orders: 418,
  ordersChange: 8.1,
  aov: 1637,
  grossMargin: 54.2,
  capitalBlocked: 312800,
  outstandingReceivables: 48600,
};

export const revenueByMonth = [
  { month: "Jan", revenue: 42000 },
  { month: "Feb", revenue: 48500 },
  { month: "Mar", revenue: 51200 },
  { month: "Apr", revenue: 57800 },
  { month: "May", revenue: 61000 },
  { month: "Jun", revenue: 68200 },
  { month: "Jul", revenue: 71500 },
];

export const channelMix = [
  { channel: "Shopify D2C", share: 48, revenue: 328400 },
  { channel: "Institutional", share: 22, revenue: 150500 },
  { channel: "Pop-ups", share: 15, revenue: 102600 },
  { channel: "WhatsApp", share: 10, revenue: 68400 },
  { channel: "Wholesale", share: 5, revenue: 34300 },
];

export const sampleAdvice: Record<
  string,
  { answer: string; actions: { label: string; href: string }[] }
> = {
  "What should I manufacture before Navarathri?": {
    answer:
      "Navarathri demand historically concentrates on Amman Stories books, Ganapathi magnets, and Lakshmi ritual objects. Your book stock (120) is healthy; magnets (210) can support a 500-unit festival push. Brass tumblers are thin at 18 units — Moradabad lead time is ~28 days, so place a reorder of 80–100 this week if you want them on shelves by early September. Pair bottles from the Muruga world as gift companions rather than a primary Navarathri SKU.",
    actions: [
      { label: "Start Manufacturing", href: "/manufacture" },
      { label: "Create Project", href: "/projects" },
      { label: "Review Inventory", href: "/dashboard" },
    ],
  },
  "Can I fulfil a 100-piece hamper order?": {
    answer:
      "Yes, with a Chennai-rooted mix using existing inventory: Market Totes (64 on hand — reorder 50+), Ganapathi magnets (210), and Amman Stories books (120). For 100 hampers at ~₹1,200–1,500 budget, cost sits near ₹680–820/unit if you lean on magnets + book + small pouch. Bottleneck is totes — start a quick reorder with Kanchi Weave (MOQ 75, ~21 days) or substitute pouches (88 on hand) for part of the run.",
    actions: [
      { label: "Build Hamper", href: "/story" },
      { label: "Start Manufacturing", href: "/manufacture" },
      { label: "Add to Priorities", href: "/" },
    ],
  },
  "Which products are blocking the most capital?": {
    answer:
      "Capital blocked totals ~₹3.13L. Highest binders: Kolam Framed Art (slow, high unit cost, only 7 left but ₹890 cost each sitting cold), Carnatic Raga Trays (11 units × ₹720), and brass tumblers mid-pipeline (PO-2398 partial). Fast movers — bottles and magnets — turn capital quickly. Consider a framed-art clearance bundle and pause tray reorder until velocity improves.",
    actions: [
      { label: "Review Inventory", href: "/dashboard" },
      { label: "Create Project", href: "/projects" },
    ],
  },
  "What should I look for in Moradabad?": {
    answer:
      "For the sourcing trip: (1) finish consistency on davara rims — last partial had scuffing, (2) ability to drop MOQ to 40 for trial SKUs, (3) sample three patina levels for Lakshmi line, (4) tray weight vs shipping cost for Carnatic Raga Tray, (5) packaging that survives courier without foam waste. Ask for written lead-time SLAs ahead of Navarathri.",
    actions: [
      { label: "Open Project", href: "/projects/prj-5" },
      { label: "Start Manufacturing", href: "/manufacture" },
    ],
  },
  "Should I reorder bottles now?": {
    answer:
      "Muruga bottles: 42 on hand + 200 in production (PO-2401, due Aug 10). At current velocity you will be fine through August. Do not double-order unless you commit a Navarathri gift set. If you want a second colourway, wait for PO-2401 QC before placing another 100.",
    actions: [
      { label: "Review Inventory", href: "/dashboard" },
      { label: "Receive Stock", href: "/receive" },
      { label: "Add to Priorities", href: "/" },
    ],
  },
};

export function exploreIdea(theme: string): IdeaExploration {
  const t = theme.trim() || "Muruga";
  return {
    worlds: [t, `${t} & Everyday Ritual`, `Contemporary ${t}`],
    stories: [
      `${t} as a morning companion`,
      `Passing ${t} stories across generations`,
      `${t} in the city — temple steps to studio desks`,
    ],
    objects: [
      "Water bottle",
      "Fridge magnet set",
      "Pouch",
      "Brass tumbler",
      "Story card pack",
      "Framed art print",
    ],
    experiences: [
      "Desk ritual kit",
      "Festival gifting hamper",
      "Children's story hour bundle",
      "Studio / office welcome set",
    ],
    customerSegments: [
      "Urban diaspora families",
      "Design-conscious professionals",
      "Parents of 4–10 year olds",
      "Institutional gifting buyers",
      "Temple & cultural event organisers",
    ],
    existingProducts: products
      .filter((p) => p.world.toLowerCase().includes(t.toLowerCase()) || t.length < 3)
      .slice(0, 4)
      .map((p) => p.name)
      .concat(
        products
          .filter((p) => !p.world.toLowerCase().includes(t.toLowerCase()))
          .slice(0, 2)
          .map((p) => p.name),
      )
      .slice(0, 4),
    productOpportunities: [
      {
        id: "opp-1",
        name: `${t} Water Bottle — Indigo`,
        rationale: `Extends proven bottle format into a ${t}-led colour story for desks and travel.`,
        moq: 100,
        unitCost: 335,
        estimatedCapital: 33500,
        vendor: "Sri Velan Bottles",
      },
      {
        id: "opp-2",
        name: `${t} Magnet Triptych`,
        rationale: "Low capital, high giftability, strong festival and institutional attach rate.",
        moq: 200,
        unitCost: 92,
        estimatedCapital: 18400,
        vendor: "Pondy Print House",
      },
      {
        id: "opp-3",
        name: `${t} Story Pouch + Card`,
        rationale: "Textile + narrative combo for hampers without heavy inventory risk.",
        moq: 75,
        unitCost: 210,
        estimatedCapital: 15750,
        vendor: "Kanchi Weave Studio",
      },
    ],
    relevantVendors: [
      "Sri Velan Bottles",
      "Pondy Print House",
      "Kanchi Weave Studio",
      "Moradabad Brass Collective",
    ],
  };
}

export const launchChecklists: LaunchChecklist[] = [
  {
    id: "lc-1",
    productName: "Muruga Water Bottle — Indigo",
    category: "Water bottles",
    world: "Muruga",
    story: "A daily vessel for devotion that travels from home altar to office desk.",
    description:
      "750ml dual-wall bottle with Muruga line illustration in warm cream on deep indigo.",
    sellingPrice: 920,
    cost: 335,
    inventory: 0,
    photosReady: false,
    barcodeReady: false,
    shopifyReady: false,
    contentReady: false,
    launchDate: "2026-09-01",
    blockers: ["Awaiting manufacturing delivery", "Photography not booked", "Barcode not generated"],
  },
  {
    id: "lc-2",
    productName: "Navarathri Magnet Assortment",
    category: "Magnets",
    world: "Navarathri",
    story: "Nine forms, nine small joys for the fridge and the festival shelf.",
    description: "Set of 9 illustrated magnets with soft-touch laminate finish.",
    sellingPrice: 480,
    cost: 85,
    inventory: 0,
    photosReady: true,
    barcodeReady: true,
    shopifyReady: false,
    contentReady: true,
    launchDate: "2026-08-25",
    blockers: ["Stock not received", "Shopify listing draft incomplete"],
  },
  {
    id: "lc-3",
    productName: "Bharatanatyam Gesture Pouch — Gold",
    category: "Pouches",
    world: "Bharatanatyam",
    story: "A pocket for the small things that keep rhythm with the day.",
    description: "Canvas pouch with mudra motif in mustard on soft beige.",
    sellingPrice: 560,
    cost: 185,
    inventory: 40,
    photosReady: true,
    barcodeReady: true,
    shopifyReady: true,
    contentReady: false,
    launchDate: "2026-08-12",
    blockers: ["Content captions pending review"],
  },
];

export const recentProjects = projects.slice(0, 4);

export const packagingChecklistDefaults = [
  "Product checked",
  "Bubble wrap added",
  "Thank-you card added",
  "QR card added",
  "Package sealed",
  "Shipping label attached",
];

export const tipPrompts = Object.keys(sampleAdvice);
